### ISSUE TITLE
cannot load scanpy after updating to 1.4.6 via miniconda

### ISSUE THREAD

**Issue by sztankatt** [scverse/scanpy#1166]
I have upgraded to scanpy 1.4.6 in a conda environment. Since then I cannot load the package into python, as it gives me the following error: `AttributeError: module 'cairo' has no attribute 'version_info'`

```python
import scanpy
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/site-packages/scanpy/__init__.py", line 38, in <module>
    from . import plotting as pl
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import scatter, violin, ranking, clustermap, stacked_violin, heatmap, dotplot, matrixplot, tracksplot, dendrogram, correlation_matrix
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/site-packages/scanpy/plotting/_anndata.py", line 16, in <module>
    from matplotlib import pyplot as pl
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2349, in <module>
    switch_backend(rcParams["backend"])
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/site-packages/matplotlib/__init__.py", line 833, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/site-packages/matplotlib/pyplot.py", line 204, in switch_backend
    switch_backend(candidate)
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/site-packages/matplotlib/backends/backend_gtk3agg.py", line 4, in <module>
    from . import backend_agg, backend_cairo, backend_gtk3
  File "/home/tsztank/.miniconda3/envs/brandeis/lib/python3.7/site-packages/matplotlib/backends/backend_cairo.py", line 15, in <module>
    if cairo.version_info < (1, 11, 0):
AttributeError: module 'cairo' has no attribute 'version_info'
>>> 
```

I have scanpy==1.4.6, matplotlib==3.1.2

**Comment by ivirshup** [comment]
Could you try running:

```python
from matplotlib import pyplot as plt
```

in this environment?

**Comment by sztankatt** [comment]
Hi! so when installing via pip this is not an issue... somehow with conda it doesnt work

**Comment by sztankatt** [comment]
Ok so it doesnt work, again, even with pip... @ivirshup I tried the code you wrote, and it gives me the same error:

`` AttributeError: module 'cairo' has no attribute 'version_info'

**Comment by ivirshup** [comment]
So, it looks like the conda environment has a broken install of Matplotlib, which I don't think I can help with too much.

Are you able to create an environment with just Matplotlib, where you're able to import `pyplot`? Does adding scanpy to this environment break matplotlib?
