### ISSUE TITLE
Having anndata issue in Clustering 3K PBMCs Following a Seurat Tutorial 

### ISSUE THREAD

**Issue by vikramsunkara** [scverse/scanpy#734]
Heya,

I have been trying to get scanpy loaded and a simple example up and running. 

I tried following the " Clustering 3K PBMCs Following a Seurat Tutorial" by trying to execute the following code:

```py
import numpy as np
import pandas as pd
import scanpy as sc
import pdb

sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_versions()

results_file = './write/pbmc3k.h5ad'  # the file that will store the analysis result

sc.settings.set_figure_params(dpi=80)

adata = sc.read_10x_mtx( 'filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)                               


adata.var_names_make_unique()  # this is unnecessary if using 'gene_ids'
print(adata)

sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)

pdb.set_trace()
```

It sadly spits out the following output (see below), it seems like a mismatch of data structures somewhere inside the code. Or I hope I am trying to run an out of date example file.

Thanks for all your help in advance.
Cheers.

```pytb
> scanpy==1.4.3 anndata==0.6.22.post1 umap==0.3.9 numpy==1.16.4 scipy==1.3.0 pandas==0.24.2 scikit-learn==0.21.2 statsmodels==0.10.0 
... reading from cache file cache/filtered_gene_bc_matrices-hg19-matrix.h5ad
AnnData object with n_obs × n_vars = 2700 × 32738 
    var: 'gene_ids'

Traceback (most recent call last):
  File "test.py", line 23, in <module>
    sc.pp.filter_cells(adata, min_genes=200)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scanpy/preprocessing/_simple.py", line 126, in filter_cells
    adata._inplace_subset_obs(cell_subset)
  File "/Users/Person/Library/Python/3.6/lib/python/site-packages/anndata-0.6.22.post1-py3.6.egg/anndata/core/anndata.py", line 1372, in _inplace_subset_obs
    adata_subset = self[index].copy()
  File "/Users/Person/Library/Python/3.6/lib/python/site-packages/anndata-0.6.22.post1-py3.6.egg/anndata/core/anndata.py", line 1230, in __getitem__
    return self._getitem_view(index)
  File "/Users/Person/Library/Python/3.6/lib/python/site-packages/anndata-0.6.22.post1-py3.6.egg/anndata/core/anndata.py", line 1234, in _getitem_view
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/Users/Person/Library/Python/3.6/lib/python/site-packages/anndata-0.6.22.post1-py3.6.egg/anndata/core/anndata.py", line 561, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/Users/Person/Library/Python/3.6/lib/python/site-packages/anndata-0.6.22.post1-py3.6.egg/anndata/core/anndata.py", line 621, in _init_as_view
    self._obs = DataFrameView(obs_sub, view_args=(self, 'obs'))
  File "/Users/Person/Library/Python/3.6/lib/python/site-packages/anndata-0.6.22.post1-py3.6.egg/anndata/core/views.py", line 41, in __init__
    view_args = ViewArgs(*view_args)
TypeError: __new__() missing 1 required positional argument: 'keys'
```

**Comment by ivirshup** [comment]
Thanks for the bug report! Thats definitely strange, since we should almost certainly be catching that in the tests...

What's the full version string of python you're runnning?

Could you also try running this snippet with the same interpreter?

```python
from typing import Tuple, NamedTuple

class ViewArgs(NamedTuple):
    parent: "AnnData"
    attrname: str
    keys: Tuple[str, ...] = ()

print(ViewArgs(None, "a"))
```

**Comment by vikramsunkara** [comment]
I am running Python 3.6.0.

The following is the output of running just the snippet above:

>   File "test.py", line 13, in <module>
    print(ViewArgs(None, "a"))
TypeError: __new__() missing 1 required positional argument: 'keys'

**Comment by ivirshup** [comment]
I think the issue might be with the version of python, since that snippet works fine for me with a fresh python 3.6 conda environment (v3.6.8) and seems to be working in our builds (v3.6.7).

Are you able to upgrade to one of those?

**Comment by vikramsunkara** [comment]
I updated it to python 3.6.8 and it gets past that error point. 
Thank you very much for all your help.
Cheers.

**Comment by ivirshup** [comment]
No worries!
