### ISSUE TITLE
No attribute 'ingest'

### ISSUE THREAD

**Issue by sarajimenez** [scverse/scanpy#1092]
Hello,

Thank you for developing and maintaining such a useful tool!
I'm trying to integrate two data sets, they're replicates of the same condition. 

```
var_names = adata_002.var_names.intersection(adata_003.var_names)
adata_002 = adata_002[:, var_names]
adata_003 = adata_003[:, var_names]

sc.pp.pca(adata_002)
sc.pp.neighbors(adata_002)
sc.tl.umap(adata_002)

sc.tl.ingest(adata_003, adata_002, obs='louvain')
```

And I got the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-b3f5427509ba> in <module>
----> 1 sc.tl.ingest(adata_003, adata_002, obs='louvain')

AttributeError: module 'scanpy.tools' has no attribute 'ingest'
```

scanpy==1.4.4.post1 anndata==0.6.22.post1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==1.0.1 scikit-learn==0.22.2.post1 statsmodels==0.11.1 python-igraph==0.7.1 louvain==0.6.1

I've already tried installing the package both with conda and pip and I continue having the same issue. 

I would really appreciate your comments and suggestions. 

Sara

**Comment by Koncopd** [comment]
Hi, @sarajimenez 
there is no ingest in scanpy 1.4.4.post1. You need to update scanpy to 1.4.5 and anndata to 0.7 to use ingest.

**Comment by vikram0010** [comment]
Hi, 
     I'm having similar issues in using sc.tl.ingest(adata, adata_ref, obs='louvain').
     I have updated my Scanpy 1.4.6 and anndata to 0.7.1.
I'm getting the following error message.
```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-71-27e22cc8f823> in <module>
----> 1 sc.tl.ingest(adata, adata_ref, obs='louvain')

~/opt/anaconda3/lib/python3.7/site-packages/scanpy/tools/_ingest.py in ingest(adata, adata_ref, obs, embedding_method, labeling_method, inplace, **kwargs)
    119 
    120     for method in embedding_method:
--> 121         ing.map_embedding(method)
    122 
    123     if obs is not None:

~/opt/anaconda3/lib/python3.7/site-packages/scanpy/tools/_ingest.py in map_embedding(self, method)
    407         """
    408         if method == 'umap':
--> 409             self._obsm['X_umap'] = self._umap_transform()
    410         elif method == 'pca':
    411             self._obsm['X_pca'] = self._pca()

~/opt/anaconda3/lib/python3.7/site-packages/scanpy/tools/_ingest.py in _umap_transform(self)
    396 
    397     def _umap_transform(self):
--> 398         return self._umap.transform(self._obsm['rep'])
    399 
    400     def map_embedding(self, method):

~/opt/anaconda3/lib/python3.7/site-packages/umap/umap_.py in transform(self, X)
   2006             try:
   2007                 # sklearn pairwise_distances fails for callable metric on sparse data
-> 2008                 _m = self.metric if self._sparse_data else self._input_distance_func
   2009                 dmat = pairwise_distances(
   2010                     X, self._raw_data, metric=_m, **self._metric_kwds

AttributeError: 'UMAP' object has no attribute '_input_distance_func'
```

Appreciate your comments.

**Comment by Koncopd** [comment]
Hi, @vikram0010 .
Downgrading umap to 0.39 should help.

**Comment by SandraWiedenmann** [comment]
Hi,

when I tried the ingest tutorial, I also got the same error, also after updating scanpy from 1.4.6 to 1.5.0 and 1.5.1.

`sc.settings.verbosity = 2  # a bit more logging
for iadata, adata in enumerate(adatas):
    print(f'... integrating batch {iadata+1}')
    adata.obs['celltype_orig'] = adata.obs['original Clusters']  # save the original cell type
    sc.tl.ingest(adata, adata_ref, obs='original Clusters')`

results in the following error:

`... integrating batch 1

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-e89f12548c8c> in <module>
      3     print(f'... integrating batch {iadata+1}')
      4     adat.obs['celltype_orig'] = adat.obs['original Clusters']  # save the original cell type
----> 5     sc.tl.ingest(adat, adata_ref, obs='cluster')

AttributeError: module 'scanpy.api.tl' has no attribute 'ingest'

`

`scanpy==1.5.1 anndata==0.7.4 umap==0.3.10 numpy==1.17.4 scipy==1.5.1 pandas==1.0.5 scikit-learn==0.22 statsmodels==0.10.1 python-igraph==0.7.1 louvain==0.6.1`

I'd appreciate any suggestions or solutions :)

Best,
Sandra
