### ISSUE TITLE
umap 0.5 compatibility

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1509]
It'd be good to make sure everything works with umap 0.5 before it get's released.

**Comment by ivirshup** [comment]
It looks like the new release breaks most of our usage from (at least) a change in arguments to `simplicial_set_embedding` (ping @Koncopd).

<details>
<summary> Example error </summary>


```pytb
            n_epochs = 0 if maxiter is None else maxiter
>           X_umap = simplicial_set_embedding(
                X,
                neighbors['connectivities'].tocoo(),
                n_components,
                alpha,
                a,
                b,
                gamma,
                negative_sample_rate,
                n_epochs,
                init_coords,
                random_state,
                neigh_params.get('metric', 'euclidean'),
                neigh_params.get('metric_kwds', {}),
                verbose=settings.verbosity > 3,
E               TypeError: simplicial_set_embedding() missing 3 required positional arguments: 'densmap', 'densmap_kwds', and 'output_dens'
```

</details>

It looks like there is also a lot of cool stuff in the new release!

**Comment by Koncopd** [comment]
Thanks, i'll check.

**Comment by gokceneraslan** [comment]
This seems related to the new Densmap feature https://umap-learn.readthedocs.io/en/latest/densmap_demo.html (see https://www.biorxiv.org/content/10.1101/2020.05.12.077776v1)

Would be cool to support it in scanpy.

**Comment by ivirshup** [comment]
@gokceneraslan, have you tried `densmap`? I'm curious to hear someone's thoughts on it.

I'm also wondering if adding it as a feature would be more complicated than adding a few pass-thru parameters to `sc.tl.umap`.

**Comment by ivirshup** [comment]
Closed by #1601 and #1589
